In [1]:
import pandas as pd
import numpy as np

In [ ]:
# Task1:DataIngestion & Initial Exploration

In [5]:
df=pd.read_csv(r"C:\Users\hp\Downloads\StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [6]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [7]:
df.shape,df.columns

((1000, 8),
 Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
        'test preparation course', 'math score', 'reading score',
        'writing score'],
       dtype='object'))

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [ ]:
# Generate statistical summary for numerical columns.

In [13]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
# Task2:DataQuality&Missing Value Analysis

In [14]:
# Check if the dataset contains any missing values
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
# Task3:Overall Student Performance Analysis

In [ ]:
# Average math score
# Average reading score
# Average writing score

In [16]:
df[['math score','reading score','writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [ ]:
# Highest score in each subject
# Lowest score in each subject

In [17]:
df[['math score','reading score','writing score']].max()

math score       100
reading score    100
writing score    100
dtype: int64

In [18]:
df[['math score','reading score','writing score']].min()

math score        0
reading score    17
writing score    10
dtype: int64

In [ ]:
# Find the total score for each student (sum of all three subjects)

In [19]:
df['total_score']=df['math score']+df['reading score']+df['writing score']
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229

In [ ]:
# Task4:Gender-Based Performance Study

In [ ]:
# Calculate average scores (math, reading, writing) for each gender.

In [20]:
df.groupby('gender')[['math score','reading score','writing score']].mean()

        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

In [ ]:
# Task5:Impact of Test Preparation Course

In [21]:
df.groupby('test preparation course')[['math score','reading score','writing score']].mean()

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

In [ ]:
# Task6:Parental Education & Student Performance

In [23]:
df.groupby('parental level of education')[['math score','reading score','writing score']].mean()

                             math score  reading score  writing score
parental level of education
associate's degree            67.882883      70.927928      69.896396
bachelor's degree             69.389831      73.000000      73.381356
high school                   62.137755      64.704082      62.448980
master's degree               69.745763      75.372881      75.677966
some college                  67.128319      69.460177      68.840708
some high school              63.497207      66.938547      64.888268

In [ ]:
# Task7:Lunch Program & Academic Achievement

In [24]:
df.groupby('lunch')[['math score','reading score','writing score']].mean()

              math score  reading score  writing score
lunch
free/reduced   58.921127      64.653521      63.022535
standard       70.034109      71.654264      70.823256

In [ ]:
# Task8:Performance Categorization (Data Manipulation)

In [25]:
def performance_Category(score):
    if score >= 250:
        return "Excellent"
    elif score >= 200:
        return "Good"
    else:
        return "Needs Improvement"
df['performance_level']= df['total_score'].apply(performance_Category)
df['performance_level'].value_counts()

performance_level
Needs Improvement    444
Good                 417
Excellent            139
Name: count, dtype: int64

In [ ]:
# Task9:Top & Bottom Performers Identification

In [26]:
df.sort_values('total_score',ascending=False).head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,performance_level
916,male,group E,bachelor's degree,standard,completed,100,100,100,300,Excellent
458,female,group E,bachelor's degree,standard,none,100,100,100,300,Excellent
962,female,group E,associate's degree,standard,none,100,100,100,300,Excellent
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,Excellent
179,female,group D,some high school,standard,completed,97,100,100,297,Excellent
712,female,group D,some college,standard,none,98,100,99,297,Excellent
165,female,group C,bachelor's degree,standard,completed,96,100,100,296,Excellent
625,male,group D,some college,standard,completed,100,97,99,296,Excellent
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100,293,Excellent
149,male,group E,associate's degree,free/reduced,completed,100,100,93,293,Excellent

In [27]:
df.sort_values('total_score').head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total_score,performance_level
59,female,group C,some high school,free/reduced,none,0,17,10,27,Needs Improvement
980,female,group B,high school,free/reduced,none,8,24,23,55,Needs Improvement
596,male,group B,high school,free/reduced,none,30,24,15,69,Needs Improvement
327,male,group A,some college,free/reduced,none,28,23,19,70,Needs Improvement
76,male,group E,some high school,standard,none,30,26,22,78,Needs Improvement
17,female,group B,some high school,free/reduced,none,18,32,28,78,Needs Improvement
601,female,group C,high school,standard,none,29,29,30,88,Needs Improvement
787,female,group B,some college,standard,none,19,38,32,89,Needs Improvement
338,female,group B,some high school,free/reduced,none,24,38,27,89,Needs Improvement
211,male,group C,some college,free/reduced,none,35,28,27,90,Needs Improvement

In [ ]:
# Task10:Insights & Conclusion (Analytical Thinking)

In [ ]:
# 1)  Test Preparation Course appears to have the strongest positive impact on scores.
#  Students who completed the test preparation course consistently achieve higher average scores in 
# Mathematics, Reading, and Writing compared to those who did not complete it.

In [ ]:
# 2)Yes test preparation significantly improve scores
# Students who completed the test preparation course generally score:
#  Higher in Math
#  Higher in Reading
#  Higher in Writing

In [ ]:
# 3) Reading and writing scores are generally higher than math score.

In [ ]:
# 4) Expand Test Preparation Programs,Support Students from Lower Socio-Economic Backgrounds
# Target Mathematics Improvement-Introduce interactive learning tools.
# Increase practice-based assessments.